feat: ログイン後のリダイレクト処理実装
qin-todo-e-team/qin_gorilla_todo pull request #63
Opened 2022-03-07 08:40 UTC by MABO-310008

## 動作確認
1. /にアクセス
2. /loginにリダイレクトされることを確認
3. ログイン後/1/todoにリダイレクトされることを確認
4. /1/account/accountSettingにアクセス
5. ログアウトまたはアカウントの削除を押下
6. 再び/にアクセス
7. /loginにリダイレクトされることを確認
# キャプチャ
https://user-images.githubusercontent.com/77882967/156995772-6c357f92-ec9d-4169-b877-517e44dc8049.mov

2022-03-08 00:52 UTC, cti1650 approved these changes
LGTM!

2022-03-08 00:52 UTC, cti1650 commented
動作確認OKです！

2022-03-09 11:18 UTC, yugo-ibuki requested changes
コメント残しました。
ご確認よろしくお願いします🙇‍♂️

2022-03-09 11:18 UTC, yugo-ibuki commented on src/hooks/useRequireLogin.tsx
> +    currentUser ? router.push("/1/todo") : router.push("/login");
ここ、currentUserか、contextからuserIdとってきてパスを作って良いと思います！

2022-03-09 11:18 UTC, yugo-ibuki commented on src/pages/login/index.tsx
> +  <Button leftIcon={<FaGoogle />} onClick={() => login()}>
細かいですが、{login}で良いと思います！

2022-03-11 16:34 UTC, yugo-ibuki approved these changes
LGTM!

2022-03-11 16:36 UTC, merged